services:
  - type: web
    name: app-frontend
    runtime: node
    rootDir: apps/react
    buildCommand: |
      npm install -g pnpm
      pnpm install
      pnpm build:ssr
    startCommand: pnpm start:ssr
    buildFilter:
      paths:
        - apps/react/**
        - packages/core/**
        - packages/shared/**
        - packages/ui/**
      ignoredPaths:
        - "**/*.test.ts"
        - "**/*.test.tsx"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_REDIS_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: app-backend
    runtime: node
    rootDir: apps/server
    buildCommand: |
      npm install -g pnpm
      pnpm install
      pnpm db:gen
      pnpm build:ssr
    startCommand: pnpm start:ssr
    buildFilter:
      paths:
        - apps/server/**
        - packages/shared/**
      ignoredPaths:
        - "**/*.test.ts"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10001
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
