services:
  - type: web
    name: kick-stock
    runtime: node
    rootDir: .
    buildCommand: |
      npm install -g pnpm
      pnpm install
      cd apps/react
      pnpm build:ssr
    startCommand: cd apps/react && pnpm start:ssr
    buildFilter:
      paths:
        - apps/react/**
        - packages/core/**
        - packages/shared/**
        - packages/ui/**
      ignoredPaths:
        - "**/*.test.ts"
        - "**/*.test.tsx"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_REDIS_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: api.kick-stock
    runtime: node
    rootDir: .
    buildCommand: |
      npm install -g pnpm
      pnpm install
      cd apps/server
      pnpm db:gen
      pnpm build:ssr
    startCommand: cd apps/server && pnpm start:ssr
    buildFilter:
      paths:
        - apps/server/**
        - packages/shared/**
      ignoredPaths:
        - "**/*.test.ts"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10001
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
