services:
  - type: web
    name: app-frontend
    runtime: node
    rootDir: apps/react
    buildCommand: pnpm install && pnpm build
    startCommand: node dist/server/index.js
    buildFilter:
      paths:
        - apps/react/**
        - packages/core/**
        - packages/shared/**
        - packages/ui/**
      ignoredPaths:
        - "**/*.test.ts"
        - "**/*.test.tsx"
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: app-backend
    runtime: node
    rootDir: apps/server
    buildCommand: pnpm install && pnpm build
    startCommand: node dist/index.js
    buildFilter:
      paths:
        - apps/server/**
        - packages/shared/**
      ignoredPaths:
        - "**/*.test.ts"
    envVars:
      - key: NODE_ENV
        value: production
