name: Deploy
on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CACHE_ENV: dev
    steps:
      - uses: actions/checkout@v4

      - name: Invalidate Redis Cache
        id: invalidate-redis-cache
        run: |
          echo "Attempting to invalidate Redis cache for ${CACHE_ENV} environment..."
          response=$(curl -X POST https://kick-stock.onrender.com/api/redis/invalidate \
          -H "x-cache-secret: ${{ secrets.CACHE_SECRET }}" \
          -H "x-cache-env: ${CACHE_ENV}" \
          -w "\n%{http_code}")

          echo "Response: $response"

          if [[ $response == *"success"* ]]; then
            echo "Redis cache invalidation successful!"
          else
            echo "Redis cache invalidation might have failed. Please check the response."
            exit 1
          fi

      - name: Invalidate CDN Cache
        id: invalidate-cdn-cache
        run: |
          echo "Attempting to invalidate CDN cache for ${CACHE_ENV} environment..."
          response=$(curl -X POST https://kick-stock.onrender.com/api/cdn-cache/invalidate \
          -H "x-cache-secret: ${{ secrets.CACHE_SECRET }}" \
          -H "x-cache-env: ${CACHE_ENV}" \
          -w "\n%{http_code}")

          echo "Response: $response"

          if [[ $response == *"success"* ]]; then
            echo "CDN cache invalidation successful!"
          else
            echo "CDN cache invalidation might have failed. Please check the response."
            exit 1
          fi

      - name: Check Cache Invalidation
        if: steps.invalidate-redis-cache.outcome == 'failure' || steps.invalidate-cdn-cache.outcome == 'failure'
        run: |
          echo "Cache invalidation failed"
          exit 1
